name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask boto3 pymysql

    - name: List files in the current directory
      run: ls -al

    - name: Package the application
      run: |
        mkdir -p package
        cp app/lambda_function.py package/        # Ajuste aqui para o caminho correto
        cp app/requirements.txt package/           # Ajuste aqui se requirements.txt também estiver na pasta app
        cd package
        pip install -r requirements.txt --target .
        zip -r ../lambda_function.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name flask-api \
          --zip-file fileb://lambda_function.zip \
          --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
