name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask boto3 pymysql

    - name: Package the application
      run: |
        mkdir -p package
        cp -r * package/
        pip install -r requirements.txt --target package/

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: flask-api
        aws-region: us-east-1
        zip-file: package.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
